CREATE TABLE BOARD_MAKEUP(
BOARDNUM NUMBER PRIMARY KEY, 
USER_M VARCHAR2(50) NOT NULL, 
PASSWORD VARCHAR2(30),
BFRONT VARCHAR2(50), 
BTITLE VARCHAR2(100) NOT NULL, 
BCONTENT CLOB ,
BFILE CLOB,  
BDATE DATE, 
BHIT NUMBER, 
BLIKE NUMBER
);
CREATE SEQUENCE BOARD_SEQ;

DROP TABLE BOARD_MAKEUP;
DROP SEQUENCE BOARD_SEQ;
commit;

select *from board_makeup;

INSERT INTO	BOARD_MAKEUP VALUES (BOARD_SEQ.NEXTVAL,'golder1023','1','1','1','1','0',SYSDATE,0,0);