CREATE TABLE VIDEO_MAKEUP(
VIDEONUM NUMBER PRIMARY KEY,
USER_M VARCHAR2(50) NOT NULL,
VFRONT VARCHAR2(50), 
VTITLE VARCHAR2(100)NOT NULL, 
VDATE DATE, 
VCONTENT VARCHAR2(300), 
VHIT NUMBER , 
VLINK VARCHAR2(400), 
VIMG VARCHAR2(400),      
VLIKE NUMBER 
);


CREATE SEQUENCE VIDEO_SEQ;
commit;


drop table VIDEO_MAKEUP;
drop SEQUENCE VIDEO_SEQ;
commit;

select * from video_MAKEUP;